// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Strider.Infrastructure.Data.Context;

namespace Strider.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Strider.Infrastructure.Data.Model.Followers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FollowerId");

                    b.HasIndex("UserId");

                    b.ToTable("Followers");
                });

            modelBuilder.Entity("Strider.Infrastructure.Data.Model.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("RepostedFromId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RepostedFromId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Strider.Infrastructure.Data.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Joined")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b07b6ac9-2ddc-4c75-8e80-b05bd2fb6a80"),
                            CreatedAt = new DateTime(2022, 4, 17, 6, 17, 22, 942, DateTimeKind.Local).AddTicks(3931),
                            IsDelete = false,
                            Joined = new DateTime(2022, 4, 17, 6, 17, 22, 943, DateTimeKind.Local).AddTicks(4866),
                            Username = "User01"
                        },
                        new
                        {
                            Id = new Guid("d9f75b0f-0f51-4a91-943f-09ae73652d12"),
                            CreatedAt = new DateTime(2022, 4, 17, 6, 17, 22, 943, DateTimeKind.Local).AddTicks(5223),
                            IsDelete = false,
                            Joined = new DateTime(2022, 4, 17, 6, 17, 22, 943, DateTimeKind.Local).AddTicks(5228),
                            Username = "User02"
                        },
                        new
                        {
                            Id = new Guid("a15c5a11-fab6-4ee9-9744-da54ffbba68d"),
                            CreatedAt = new DateTime(2022, 4, 17, 6, 17, 22, 943, DateTimeKind.Local).AddTicks(5231),
                            IsDelete = false,
                            Joined = new DateTime(2022, 4, 17, 6, 17, 22, 943, DateTimeKind.Local).AddTicks(5232),
                            Username = "User03"
                        });
                });

            modelBuilder.Entity("Strider.Infrastructure.Data.Model.Followers", b =>
                {
                    b.HasOne("Strider.Infrastructure.Data.Model.User", "Follower")
                        .WithMany()
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Strider.Infrastructure.Data.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Follower");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Strider.Infrastructure.Data.Model.Post", b =>
                {
                    b.HasOne("Strider.Infrastructure.Data.Model.Post", "RepostedFrom")
                        .WithMany()
                        .HasForeignKey("RepostedFromId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Strider.Infrastructure.Data.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RepostedFrom");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
